# Generated by Django 3.0.4 on 2020-04-07 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_performancedata_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='testStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('publisheddate', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('middlename', models.CharField(max_length=25)),
                ('jobtitle', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('officephone', models.CharField(max_length=25)),
                ('cellphone', models.CharField(max_length=25)),
                ('prefix', models.CharField(max_length=25)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('isfirequired', models.CharField(max_length=25)),
                ('fifrequency', models.CharField(max_length=25)),
                ('standardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.testStandard')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=25)),
                ('address2', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('postalcode', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(max_length=25)),
                ('faxnumber', models.CharField(max_length=25)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportnumber', models.CharField(max_length=25)),
                ('issuedate', models.CharField(max_length=25)),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.location')),
                ('modelNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('standardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.testStandard')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
